name: dbt_Logistic
version: 1.0.0
config-version: 2

profile: dbt_Logistic

model-paths:
  - models

analysis-paths:
  - analyses

test-paths:
  - tests

seed-paths:
  - seeds

macro-paths:
  - macros

snapshot-paths:
  - snapshots

models:
  dbt_Logistic:

    BRONZE:
      +schema: BRONZE
      +materialized: table

    SILVER:
      +schema: SILVER
      +materialized: table

    GOLD:
      +schema: GOLD
      +materialized: table